# TCL File Generated by Component Editor 17.1
# Thu Apr 14 13:24:02 EDT 2022
# DO NOT MODIFY


# 
# bstream_old "Bitstream Controller 256x128bit Old" v1.0
# David Ariando 2022.04.14.13:24:02
# The bitstream controller receives bitstream pattern from the internal SRAM (programmed before execution) and putting its output into IOs or internal signals.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bstream_old
# 
set_module_property DESCRIPTION "The bitstream controller receives bitstream pattern from the internal SRAM (programmed before execution) and putting its output into IOs or internal signals."
set_module_property NAME bstream_old
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Logics"
set_module_property AUTHOR "David Ariando"
set_module_property DISPLAY_NAME "Bitstream Controller 256x128bit Old"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL NMR_bstrm_arb_mm_comp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file NMR_bstrm_arb_cnt.sv SYSTEM_VERILOG PATH ../Quartus_NoSoC/HDL/NMR_bstrm_arb_cnt.sv
add_fileset_file NMR_bstrm_arb_dpath.sv SYSTEM_VERILOG PATH ../Quartus_NoSoC/HDL/NMR_bstrm_arb_dpath.sv
add_fileset_file NMR_bstrm_arb_mm_comp.sv SYSTEM_VERILOG PATH ../Quartus_NoSoC/HDL/NMR_bstrm_arb_mm_comp.sv TOP_LEVEL_FILE
add_fileset_file NMR_bstrm_arb_top.sv SYSTEM_VERILOG PATH ../Quartus_NoSoC/HDL/NMR_bstrm_arb_top.sv
add_fileset_file bstream_ram_256.qip OTHER PATH ../Quartus_NoSoC/HDL/Altera_IP/bstream_ram_256.qip


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 120
set_parameter_property DATA_WIDTH DEFAULT_VALUE 120
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH ENABLED false
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter CNT_WIDTH INTEGER 32
set_parameter_property CNT_WIDTH DEFAULT_VALUE 32
set_parameter_property CNT_WIDTH DISPLAY_NAME CNT_WIDTH
set_parameter_property CNT_WIDTH TYPE INTEGER
set_parameter_property CNT_WIDTH ENABLED false
set_parameter_property CNT_WIDTH UNITS None
set_parameter_property CNT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CNT_WIDTH HDL_PARAMETER true
add_parameter CMD_WIDTH INTEGER 8 ""
set_parameter_property CMD_WIDTH DEFAULT_VALUE 8
set_parameter_property CMD_WIDTH DISPLAY_NAME CMD_WIDTH
set_parameter_property CMD_WIDTH WIDTH ""
set_parameter_property CMD_WIDTH TYPE INTEGER
set_parameter_property CMD_WIDTH ENABLED false
set_parameter_property CMD_WIDTH UNITS None
set_parameter_property CMD_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CMD_WIDTH DESCRIPTION ""
set_parameter_property CMD_WIDTH HDL_PARAMETER true
add_parameter LOOP_WIDTH INTEGER 16
set_parameter_property LOOP_WIDTH DEFAULT_VALUE 16
set_parameter_property LOOP_WIDTH DISPLAY_NAME LOOP_WIDTH
set_parameter_property LOOP_WIDTH TYPE INTEGER
set_parameter_property LOOP_WIDTH ENABLED false
set_parameter_property LOOP_WIDTH UNITS None
set_parameter_property LOOP_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LOOP_WIDTH HDL_PARAMETER true
add_parameter SRAM_ADDR_WIDTH INTEGER 8
set_parameter_property SRAM_ADDR_WIDTH DEFAULT_VALUE 8
set_parameter_property SRAM_ADDR_WIDTH DISPLAY_NAME SRAM_ADDR_WIDTH
set_parameter_property SRAM_ADDR_WIDTH TYPE INTEGER
set_parameter_property SRAM_ADDR_WIDTH UNITS None
set_parameter_property SRAM_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SRAM_ADDR_WIDTH HDL_PARAMETER true
add_parameter SRAM_DAT_WIDTH INTEGER 128
set_parameter_property SRAM_DAT_WIDTH DEFAULT_VALUE 128
set_parameter_property SRAM_DAT_WIDTH DISPLAY_NAME SRAM_DAT_WIDTH
set_parameter_property SRAM_DAT_WIDTH TYPE INTEGER
set_parameter_property SRAM_DAT_WIDTH ENABLED false
set_parameter_property SRAM_DAT_WIDTH UNITS None
set_parameter_property SRAM_DAT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SRAM_DAT_WIDTH HDL_PARAMETER true
add_parameter MM_WIDTH INTEGER 32
set_parameter_property MM_WIDTH DEFAULT_VALUE 32
set_parameter_property MM_WIDTH DISPLAY_NAME MM_WIDTH
set_parameter_property MM_WIDTH TYPE INTEGER
set_parameter_property MM_WIDTH UNITS None
set_parameter_property MM_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_WIDTH HDL_PARAMETER true
add_parameter SRAM_BYTEEN_WIDTH INTEGER 16
set_parameter_property SRAM_BYTEEN_WIDTH DEFAULT_VALUE 16
set_parameter_property SRAM_BYTEEN_WIDTH DISPLAY_NAME SRAM_BYTEEN_WIDTH
set_parameter_property SRAM_BYTEEN_WIDTH TYPE INTEGER
set_parameter_property SRAM_BYTEEN_WIDTH ENABLED false
set_parameter_property SRAM_BYTEEN_WIDTH UNITS None
set_parameter_property SRAM_BYTEEN_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SRAM_BYTEEN_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock wr_clk
set_interface_property s0 associatedReset rst
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input SRAM_ADDR_WIDTH
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input SRAM_DAT_WIDTH
add_interface_port s0 avs_s0_byteena_a byteenable Input SRAM_BYTEEN_WIDTH
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rd_clk
# 
add_interface rd_clk clock end
set_interface_property rd_clk clockRate 0
set_interface_property rd_clk ENABLED true
set_interface_property rd_clk EXPORT_OF ""
set_interface_property rd_clk PORT_NAME_MAP ""
set_interface_property rd_clk CMSIS_SVD_VARIABLES ""
set_interface_property rd_clk SVD_ADDRESS_GROUP ""

add_interface_port rd_clk csi_RD_CLK clk Input 1


# 
# connection point wr_clk
# 
add_interface wr_clk clock end
set_interface_property wr_clk clockRate 0
set_interface_property wr_clk ENABLED true
set_interface_property wr_clk EXPORT_OF ""
set_interface_property wr_clk PORT_NAME_MAP ""
set_interface_property wr_clk CMSIS_SVD_VARIABLES ""
set_interface_property wr_clk SVD_ADDRESS_GROUP ""

add_interface_port wr_clk csi_WR_CLK clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock rd_clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rsi_RST reset Input 1


# 
# connection point cntl
# 
add_interface cntl conduit end
set_interface_property cntl associatedClock rd_clk
set_interface_property cntl associatedReset rst
set_interface_property cntl ENABLED true
set_interface_property cntl EXPORT_OF ""
set_interface_property cntl PORT_NAME_MAP ""
set_interface_property cntl CMSIS_SVD_VARIABLES ""
set_interface_property cntl SVD_ADDRESS_GROUP ""

add_interface_port cntl coe_START start Input 1
add_interface_port cntl coe_DONE done Output 1
add_interface_port cntl coe_OUT out Output 1

